Add enable / disable at boot

diff --git a/anonsurf/anonsurf b/anonsurf/anonsurf
--- a/anonsurf/anonsurf
+++ b/anonsurf/anonsurf
@@ -108,8 +108,27 @@ function stop {
 }
 
 
+function enable-boot {
+	if [ "$(systemctl list-unit-files | grep anondaemon | awk '{print $2}')" = "disabled" ]; then
+		systemctl enable anondaemon;
+		notify "Enabling AnonSurf at boot"
+	else
+		echo -e "\n$GREEN[$RED!$GREEN] $RED Anonsurf already enabled!$RESETCOLOR\n"
+	fi
+}
+
+
+function disable-boot {
+	if [ "$(systemctl list-unit-files | grep anondaemon | awk '{print $2}')" = "enabled" ]; then
+		systemctl enable anondaemon;
+		notify "Disabling AnonSurf at boot"
+	else
+		echo -e "\n$GREEN[$RED!$GREEN] $RED AnonSurf wasn't enabled. Nothing to disable!$RESETCOLOR\n"
+	fi
+}
+
+
 function change {
-	checkuid
 	echo -e "authenticate \"kuhNygbtfu76fFUbgv\"\nsignal newnym\nquit" | nc localhost -q 1 9051
 	service tor restart
 	sleep 1
@@ -168,7 +187,7 @@ case "$1" in
 			zenity --question --text="Do you want anonsurf to kill dangerous applications and clean some application caches?" --width 400 && init
 			start
 		else
-			echo -e "\n$GREEN[$RED!$GREEN] $RED Anonsurf is running! Can't start service!$RESETCOLOR\n" >&2
+			echo -e "\n$GREEN[$RED!$GREEN] $RED AnonSurf is running! Can't start service!$RESETCOLOR\n" >&2
 		fi
 	;;
 	stop)
@@ -178,24 +197,25 @@ case "$1" in
 			zenity --question --text="Do you want anonsurf to kill dangerous applications and clean some application caches?" --width 400 && init
 			stop
 		else
-			echo -e "\n$GREEN[$RED!$GREEN] $RED Anonsurf is not running! Can't stop service!$RESETCOLOR\n" >&2
+			echo -e "\n$GREEN[$RED!$GREEN] $RED AnonSurf is not running! Can't stop service!$RESETCOLOR\n" >&2
 		fi
 	;;
 	changeid|change-id|change)
+		checkuid
 		change
 	;;
 	status)
 		if [ "$(service anondaemon status | grep Active | awk '{print $2}')" = "active" ]; then
 			status
 		else
-			echo -e "\n$GREEN[$RED!$GREEN] $RED Anonsurf is not running!$RESETCOLOR\n"
+			echo -e "\n$GREEN[$RED!$GREEN] $RED AnonSurf is not running!$RESETCOLOR\n"
 		fi
 	;;
 	myip|ip)
 		ip
 	;;
 	dns)
-	    dns
+		dns
 	;;
 	restart)
 		# Restart if the daemon is running onnly
@@ -205,8 +225,16 @@ case "$1" in
 			sleep 1
 			$0 start
 		else
-			echo -e "\n$GREEN[$RED!$GREEN] $RED Anonsurf is not running! Can't restart service!$RESETCOLOR\n" >&2
+			echo -e "\n$GREEN[$RED!$GREEN] $RED AnonSurf is not running! Can't restart service!$RESETCOLOR\n" >&2
 		fi
+	;;
+	enable-boot)
+		checkuid
+		enable-boot
+	;;
+	disable-boot)
+		checkuid
+		disable-boot
 	;;
    *)
 echo -e "
@@ -220,11 +248,13 @@ Parrot AnonSurf Module (v 2.11)
 
 	Usage:
 	$RED┌──[$GREEN$USER$YELLOW@$BLUE`hostname`$RED]─[$GREEN$PWD$RED]
-	$RED└──╼ \$$GREEN"" anonsurf $RED{$GREEN""start$RED|$GREEN""stop$RED|$GREEN""restart$RED|$GREEN""change$RED""$RED|$GREEN""status$RED""}
+	$RED└──╼ \$$GREEN"" anonsurf $RED{$GREEN""start$RED|$GREEN""stop$RED|$GREEN""restart$RED|$GREEN""enable-boot$RED|$GREEN""disable-boot$RED|$GREEN""change$RED""$RED|$GREEN""status$RED""}
 
 	$RED start$BLUE -$GREEN Start system-wide TOR tunnel
 	$RED stop$BLUE -$GREEN Stop anonsurf and return to clearnet
 	$RED restart$BLUE -$GREEN Combines \"stop\" and \"start\" options
+	$RED enable-boot$BLUE -$GREEN Enable AnonSurf at boot
+	$RED disable-boot$BLUE -$GREEN Disable AnonSurf at boot
 	$RED changeid$BLUE -$GREEN Restart TOR to change identity
 	$RED status$BLUE -$GREEN Check if AnonSurf is working properly
 	$RED myip$BLUE -$GREEN Check your ip and verify your tor connection
