split stop/ start services to func, rework restart

diff --git a/src/anondaemon b/src/anondaemon
--- a/src/anondaemon
+++ b/src/anondaemon
@@ -16,7 +16,7 @@ TOR_UID="debian-tor"
 # Tor's TransPort
 TOR_PORT="9040"
 
-function start {
+function disableService {
 	if [ ! -e /tmp/tor.pid ]; then
 		echo -e " $RED*$BLUE Tor is not running! $GREEN starting it $BLUE for you" >&2
 		echo -e -n "\n $GREEN*$BLUE Stopping service nscd"
@@ -28,10 +28,21 @@ function start {
 		killall dnsmasq nscd resolvconf 2>/dev/null || true
 		sleep 2
 		killall -9 dnsmasq 2>/dev/null || true
-		systemctl start tor
-		sleep 20
 	fi
+}
 
+function enableService {
+	echo -e -n "\ $GREEN*$BLUE Restarting services\n"
+	/usr/sbin/service resolvconf start || service resolvconf restart || true
+	/usr/sbin/service dnsmasq start || true
+	/usr/sbin/service nscd start || true
+	echo -e " $GREEN*$BLUE It is safe to not worry for dnsmasq and nscd start errors if they are not installed or started already."
+	sleep 1
+}
+
+function start {
+	systemctl start tor
+	sleep 5
 
 	if ! [ -f /etc/network/iptables.rules ]; then
 		/usr/sbin/iptables-save > /etc/network/iptables.rules
@@ -107,24 +118,22 @@ function stop {
 	sleep 2
 	killall tor
 	sleep 6
-	echo -e -n "\ $GREEN*$BLUE Restarting services\n"
-	/usr/sbin/service resolvconf start || service resolvconf restart || true
-	/usr/sbin/service dnsmasq start || true
-	/usr/sbin/service nscd start || true
-	echo -e " $GREEN*$BLUE It is safe to not worry for dnsmasq and nscd start errors if they are not installed or started already."
-	sleep 1
-
 }
 
 
 case "$1" in
 	start)
+		# TODO start if the daemon is not running only
+		disableService
 		start
 	;;
 	stop)
+		# TODO stop if the daemon is running only
 		stop
+		enableService
 	;;
 	restart)
+		# TODO restart if the daemon is running onnly
 		$0 stop
 		sleep 1
 		$0 start
